### ISSUE TITLE
Uploading any PDF file using any model "Cannot destructure property 'markdown' of 'e' as it is undefined"

### ISSUE THREAD

**Issue by gvisniuc** [OpenHealthForAll/open-health#37]
Hi there,

Thanks a lot for this project!

I was giving it a try and I cannot upload any PDF files regardless of the model or the content of the PDF file.

```
app-1       | Error processing file: TypeError: Cannot destructure property 'markdown' of 'e' as it is undefined.
app-1       |     at aV (.next/server/app/api/health-data/route.js:24:116115)
app-1       |     at async aB (.next/server/app/api/health-data/route.js:64:1828)
app-1       |     at async aZ (.next/server/app/api/health-data/route.js:64:2620)
app-1       |     at async aG (.next/server/app/api/health-data/route.js:64:3878)
```

I tried:
- 4 or 5 different PDFs
- A PNG file
- Different models (4o, o1-mini, Ollama)
- Different browsers (Chrome, Brave)

**Comment by GwonHyeok** [comment]
@gvisniuc 

You can check the /public/uploads/*.json file in the docker volume.

Please attach the contents of the JSON file here for troubleshooting.

**Comment by gvisniuc** [comment]
Hi all, thanks for the help.

@GwonHyeok indeed when checking the `/public/uploads` folder I have found a .json file with the content 
```
{"error":{"message":"API key is invalid, please check out our API reference page (https://console.upstage.ai/docs/getting-started/overview)","type":"invalid_request_error","param":"","code":"invalid_api_key"}
```

However @salveandtango when setting the .env UPSTAGE variable it would not be transferred to the container even after restart/repo re-clone.

I ended up adding the to the `docker-compose.yaml` file

```
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      UPSTAGE_API_KEY: ${UPSTAGE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
```


Also after I have deleted all the files in the `/public/uploads`, then it started working fine!
